// Package artifacts provides storage and management for tool-produced artifacts.
// This includes screenshots, recordings, and other files generated by edge tools.
package artifacts

import (
	"context"
	"io"
	"time"

	pb "github.com/haasonsaas/nexus/pkg/proto"
)

// Store provides persistent storage for artifact binary data.
// Implementations can target local disk, S3, MinIO, etc.
type Store interface {
	// Put stores artifact data and returns a reference URL/ID.
	Put(ctx context.Context, artifactID string, data io.Reader, opts PutOptions) (reference string, err error)

	// Get retrieves artifact data by ID.
	Get(ctx context.Context, artifactID string) (io.ReadCloser, error)

	// Delete removes an artifact from storage.
	Delete(ctx context.Context, artifactID string) error

	// Exists checks if an artifact exists.
	Exists(ctx context.Context, artifactID string) (bool, error)

	// Close releases any resources.
	Close() error
}

// PutOptions configures artifact storage behavior.
type PutOptions struct {
	// MimeType for the stored data.
	MimeType string

	// TTL is time-to-live for this artifact.
	TTL time.Duration

	// Metadata for the artifact.
	Metadata map[string]string
}

// Repository manages artifact metadata and coordinates with storage backend.
type Repository interface {
	// StoreArtifact persists an artifact from tool execution.
	StoreArtifact(ctx context.Context, artifact *pb.Artifact, data io.Reader) error

	// GetArtifact retrieves artifact metadata and data.
	GetArtifact(ctx context.Context, artifactID string) (*pb.Artifact, io.ReadCloser, error)

	// ListArtifacts finds artifacts matching criteria.
	ListArtifacts(ctx context.Context, filter Filter) ([]*pb.Artifact, error)

	// DeleteArtifact removes an artifact and its data.
	DeleteArtifact(ctx context.Context, artifactID string) error

	// PruneExpired removes expired artifacts.
	PruneExpired(ctx context.Context) (count int, err error)
}

// Filter specifies criteria for listing artifacts.
type Filter struct {
	SessionID     string
	EdgeID        string
	Type          string // screenshot, recording, file, etc
	CreatedAfter  time.Time
	CreatedBefore time.Time
	Limit         int
}

// Metadata stores artifact records (NOT the binary data).
type Metadata struct {
	ID         string
	SessionID  string
	EdgeID     string
	Type       string
	MimeType   string
	Filename   string
	Size       int64
	Reference  string
	TTLSeconds int32
	CreatedAt  time.Time
	ExpiresAt  time.Time
}

// DefaultTTLs provides default retention periods by artifact type.
var DefaultTTLs = map[string]time.Duration{
	"screenshot": 7 * 24 * time.Hour,  // 7 days
	"recording":  30 * 24 * time.Hour, // 30 days
	"file":       14 * 24 * time.Hour, // 14 days
	"default":    24 * time.Hour,      // 1 day
}

// GetDefaultTTL returns the default TTL for an artifact type.
func GetDefaultTTL(artifactType string) time.Duration {
	if ttl, ok := DefaultTTLs[artifactType]; ok {
		return ttl
	}
	return DefaultTTLs["default"]
}
