run:
  timeout: 5m
  tests: false

issues:
  exclude-dirs-use-default: true

linters:
  disable-all: true
  enable:
    - govet
    - staticcheck
    - ineffassign
    - typecheck
    - unused
    - gosimple
    - errcheck
    - misspell

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  misspell:
    locale: US
    ignore-words:
      - cancelled
      - cancelling
