# Nexus Configuration Example
# Copy this file to nexus.yaml and fill in your credentials

version: 1

server:
  host: 0.0.0.0
  grpc_port: 50051
  http_port: 8080
  metrics_port: 9090

canvas_host:
  # Dedicated canvas host for local HTML/JS canvas files.
  # When enabled, the canvas is available at http://<host>:<port>/__nexus__/canvas/
  enabled: false
  # host: 0.0.0.0
  # port: 18793
  # root: ./canvas
  # namespace: /__nexus__
  # live_reload: true
  # inject_client: true
  # auto_index: true
  # a2ui_root: ./a2ui

canvas:
  retention:
    # How long to keep the latest canvas snapshot.
    state_max_age: 720h
    # How long to retain canvas events for replay.
    event_max_age: 168h
    # Maximum size of stored canvas snapshot in bytes.
    state_max_bytes: 1048576
    # Maximum size of stored canvas event payload in bytes.
    event_max_bytes: 262144
  tokens:
    # Secret used to sign canvas access tokens.
    # Generate with: openssl rand -base64 32
    secret: ${CANVAS_TOKEN_SECRET}
    ttl: 30m
  actions:
    # Role applied to authenticated requests without a signed canvas token.
    default_role: viewer
    rate_limit:
      enabled: true
      requests_per_second: 10
      burst_size: 20
  audit:
    enabled: false
    level: info
    format: json
    output: stdout

commands:
  # Enable text command handling
  enabled: true
  # Optional allowlist for command-only messages (empty = allow all)
  allow_from:
    # telegram:
    #   - "12345678"
    #   - "*"
  # Inline command shortcuts require an explicit allowlist
  inline_allow_from:
    # telegram:
    #   - "12345678"
  # Inline commands allowed to run inside normal messages
  inline_commands:
    - help
    - commands
    - status
    - whoami
    - id

database:
  # CockroachDB connection string
  # For local dev: postgres://root@localhost:26257/nexus?sslmode=disable
  # For production: postgres://user:password@host:26257/nexus?sslmode=verify-full
  url: ${DATABASE_URL:-postgres://root@localhost:26257/nexus?sslmode=disable}
  max_connections: 25
  conn_max_lifetime: 5m

auth:
  # Generate with: openssl rand -base64 32
  jwt_secret: ${JWT_SECRET}
  token_expiry: 24h
  # Optional API keys for gRPC access (used when no JWT is provided)
  api_keys:
    - key: ${NEXUS_API_KEY}
      user_id: operator
      name: "Operator key"

  oauth:
    google:
      client_id: ${GOOGLE_CLIENT_ID}
      client_secret: ${GOOGLE_CLIENT_SECRET}
      redirect_url: http://localhost:8080/auth/google/callback
    github:
      client_id: ${GITHUB_CLIENT_ID}
      client_secret: ${GITHUB_CLIENT_SECRET}
      redirect_url: http://localhost:8080/auth/github/callback

session:
  # Default agent ID used for session routing
  default_agent_id: main
  # Session scope for threaded channels: "thread" or "channel"
  slack_scope: thread
  discord_scope: thread
  # Optional local memory log
  memory:
    enabled: false
    directory: memory
    max_lines: 20
    days: 2
    scope: session # session, channel, or global
  # Optional heartbeat checklist file for heartbeat-style runs
  heartbeat:
    enabled: false
    file: HEARTBEAT.md
    mode: always # always or on_demand
  # Optional memory flush reminder when sessions grow large
  memory_flush:
    enabled: false
    threshold: 80
    prompt: "Session nearing compaction. If there are durable facts, store them in memory/YYYY-MM-DD.md or MEMORY.md. Reply NO_REPLY if nothing needs attention."

workspace:
  # Optional workspace bootstrap files (Clawdbot/Clawd-style)
  enabled: false
  path: .
  max_chars: 20000
  agents_file: AGENTS.md
  soul_file: SOUL.md
  user_file: USER.md
  identity_file: IDENTITY.md
  tools_file: TOOLS.md
  memory_file: MEMORY.md

identity:
  # Optional agent identity
  name: ""
  creature: ""
  vibe: ""
  emoji: ""

user:
  # Optional user profile
  name: ""
  preferred_address: ""
  pronouns: ""
  timezone: ""
  notes: ""

vector_memory:
  enabled: false
  backend: sqlite-vec # sqlite-vec | lancedb | pgvector
  dimension: 1536
  sqlite_vec:
    path: ~/.nexus/vector-memory.sqlite
  lancedb:
    path: ~/.nexus/lancedb
    index_type: flat
    metric_type: cosine
    n_probes: 10
    ef: 64
    refine_factor: 2
  pgvector:
    dsn: ${VECTOR_MEMORY_DSN:-}
    use_cockroachdb: false
    run_migrations: true
  embeddings:
    provider: openai
    api_key: ${OPENAI_API_KEY}
    base_url: https://api.openai.com/v1
    model: text-embedding-3-small
    ollama_url: http://localhost:11434
    project_id: ""
    location: ""
  indexing:
    auto_index_messages: false
    min_content_length: 10
    batch_size: 100
  search:
    default_limit: 10
    default_threshold: 0.7
    default_scope: session

channels:
  telegram:
    enabled: true
    # Get from @BotFather on Telegram
    bot_token: ${TELEGRAM_BOT_TOKEN}
    # Optional: webhook URL for production
    # webhook: https://your-domain.com/webhook/telegram
    dm:
      policy: open # open | allowlist | pairing | disabled
      # allow_from: ["123456789"]
    group:
      policy: allowlist
      # allow_from: ["-123456789"]

  discord:
    enabled: true
    # Get from Discord Developer Portal
    bot_token: ${DISCORD_BOT_TOKEN}
    app_id: ${DISCORD_APP_ID}
    dm:
      policy: pairing
      # allow_from: ["1234567890"]
    group:
      policy: allowlist
      # allow_from: ["123456789012345678"]

  slack:
    enabled: true
    # Get from Slack App settings
    bot_token: ${SLACK_BOT_TOKEN}      # xoxb-...
    app_token: ${SLACK_APP_TOKEN}      # xapp-... (for Socket Mode)
    signing_secret: ${SLACK_SIGNING_SECRET}
    dm:
      policy: pairing
      # allow_from: ["U1234567890"]
    group:
      policy: allowlist
      # allow_from: ["C1234567890"]
    canvas:
      enabled: false
      command: /canvas
      shortcut_callback: open_canvas
      # allowed_workspaces: ["T1234567890"]
      # default_role: editor
      # workspace_roles:
      #   T1234567890: admin
      # user_roles:
      #   T1234567890:
      #     U1234567890: viewer

llm:
  # default_provider can reference a profile (e.g., "openai:fast")
  default_provider: anthropic

  providers:
    anthropic:
      api_key: ${ANTHROPIC_API_KEY}
      default_model: claude-sonnet-4-20250514
      # Optional: for high-volume usage
      # base_url: https://api.anthropic.com

    openai:
      api_key: ${OPENAI_API_KEY}
      default_model: gpt-4o
      # Optional: for Azure OpenAI
      # base_url: https://your-resource.openai.azure.com
      profiles:
        fast:
          api_key: ${OPENAI_FAST_API_KEY}
          default_model: gpt-4o-mini

    google:
      api_key: ${GOOGLE_AI_API_KEY}
      default_model: gemini-pro

    openrouter:
      api_key: ${OPENROUTER_API_KEY}
      default_model: anthropic/claude-3.5-sonnet

tools:
  # Optional notes to include in the system prompt for tool conventions
  notes: ""
  # Optional file path with tool notes (merged with inline notes)
  notes_file: ""
  # Optional memory search tool
  memory_search:
    enabled: false
    directory: memory
    memory_file: MEMORY.md
    max_results: 5
    max_snippet_len: 200
    mode: hybrid # lexical, vector, or hybrid
    embeddings:
      provider: openai
      api_key: ${OPENAI_API_KEY}
      base_url: https://api.openai.com/v1
      model: text-embedding-3-small
      cache_dir: ~/.nexus/cache/embeddings
      cache_ttl: 24h
      timeout: 15s
  sandbox:
    enabled: true
    backend: docker # docker | firecracker
    # Number of pre-warmed sandboxes
    pool_size: 5
    max_pool_size: 10
    # Maximum execution time per request
    timeout: 30s
    network_enabled: false
    limits:
      max_cpu: 1000 # millicores
      max_memory: 512MB
  browser:
    enabled: true
    headless: true
    # Optional: connect to remote Playwright server
    # url: http://playwright:3000
  computer_use:
    enabled: false
    # Default edge to target for computer use (optional)
    edge_id: ""
    # Optional display overrides when node metadata is unavailable
    display_width_px: 0
    display_height_px: 0
    display_number: 0
  websearch:
    enabled: true
    provider: searxng
    # SearXNG instance URL
    url: ${SEARXNG_URL:-http://localhost:8888}
  web_fetch:
    enabled: true
    max_chars: 10000
  execution:
    max_iterations: 4
    parallelism: 2
    timeout: 0s
    max_attempts: 1
    retry_backoff: 0s
    disable_events: false
    max_tool_calls: 0
    require_approval: []
    approval:
      profile: coding
      allowlist: []
      denylist: []
      safe_bins: []
      skill_allowlist: true
      ask_fallback: true
      default_decision: pending
      request_ttl: 5m
    result_guard:
      enabled: false
      max_chars: 0
      denylist: []
      redact_patterns: []
      redaction_text: "[redacted]"
      truncate_suffix: "...[truncated]"
    async: []
  elevated:
    enabled: false
    allow_from:
      telegram: ["123456789"]
    tools: ["execute_code"]

artifacts:
  # Storage backend: local | s3 | minio | none
  backend: local
  # Directory for local storage and metadata
  local_path: /tmp/nexus-artifacts
  # Optional metadata file path (defaults to <local_path>/metadata.json)
  metadata_path: /tmp/nexus-artifacts/metadata.json
  # Metadata backend: file | database
  metadata_backend: file
  # S3/MinIO settings (used when backend is s3/minio)
  s3_bucket: ${NEXUS_ARTIFACTS_BUCKET}
  s3_endpoint: ${NEXUS_ARTIFACTS_ENDPOINT}
  s3_region: ${AWS_REGION:-us-east-1}
  # Cleanup interval for expired artifacts
  prune_interval: 1h
  # TTLs by artifact type
  ttls:
    screenshot: 168h
    recording: 720h
    file: 336h
    default: 24h
  redaction:
    enabled: false
    types: []
    mime_types: []
    filename_patterns: []

transcription:
  enabled: false
  provider: openai
  api_key: ${OPENAI_API_KEY}
  base_url: https://api.openai.com/v1
  model: whisper-1
  language: ""

plugins:
  # Optional plugin manifest search paths
  load:
    paths: []
  # Example plugin entry
  # entries:
  #   voice-call:
  #     enabled: true
  #     path: ./plugins/voice-call # directory containing nexus.plugin.json + plugin.so (or <id>.so)
  #     config:
  #       token: ${VOICE_CALL_TOKEN}
  #   sample-echo:
  #     enabled: true
  #     path: ./examples/plugins/echo
  #     config:
  #       prefix: "[echo] "

logging:
  level: info  # debug, info, warn, error
  format: json # json, text
  # Optional: output to file
  # file: /var/log/nexus/nexus.log
