import SwiftUI

struct ArtifactsView: View {
    @EnvironmentObject var model: AppModel
    @State private var isRefreshing = false
    @State private var selectedArtifact: Artifact?
    @State private var filterType: ArtifactTypeFilter = .all
    @State private var searchText = ""

    enum ArtifactTypeFilter: String, CaseIterable {
        case all = "All"
        case image = "Images"
        case document = "Documents"
        case code = "Code"
        case other = "Other"
    }

    var body: some View {
        VStack(alignment: .leading, spacing: 12) {
            // Header
            headerView

            // Toolbar
            toolbarView

            // Error banner
            if let error = model.lastError {
                ErrorBanner(message: error, severity: .error) {
                    model.lastError = nil
                }
                .transition(.move(edge: .top).combined(with: .opacity))
            }

            // Content
            Group {
                if isRefreshing && model.artifacts.isEmpty {
                    LoadingStateView(message: "Loading artifacts...", showSkeleton: true)
                } else if model.artifacts.isEmpty {
                    EmptyStateView(
                        icon: "photo.on.rectangle",
                        title: "No Artifacts",
                        description: "Files and images generated by agents will appear here.",
                        actionTitle: "Refresh"
                    ) {
                        refreshArtifacts()
                    }
                } else {
                    artifactsGrid
                }
            }
            .animation(.easeInOut(duration: 0.2), value: isRefreshing)
            .animation(.easeInOut(duration: 0.2), value: model.artifacts.isEmpty)

            Spacer()
        }
        .padding()
        .animation(.easeInOut(duration: 0.2), value: model.lastError)
    }

    // MARK: - Header

    private var headerView: some View {
        HStack {
            VStack(alignment: .leading, spacing: 4) {
                Text("Artifacts")
                    .font(.title2)
                Text("Files and media generated by agents")
                    .font(.caption)
                    .foregroundStyle(.secondary)
            }

            Spacer()

            // Stats
            if !model.artifacts.isEmpty {
                HStack(spacing: 12) {
                    let totalSize = model.artifacts.reduce(0) { $0 + $1.size }
                    Label("\(model.artifacts.count) files", systemImage: "doc.fill")
                        .font(.caption)
                        .foregroundStyle(.secondary)

                    Label(formatSize(totalSize), systemImage: "externaldrive.fill")
                        .font(.caption)
                        .foregroundStyle(.secondary)
                }
            }

            Button {
                refreshArtifacts()
            } label: {
                Image(systemName: "arrow.clockwise")
            }
            .disabled(isRefreshing)
        }
    }

    // MARK: - Toolbar

    private var toolbarView: some View {
        HStack(spacing: 12) {
            // Search
            HStack {
                Image(systemName: "magnifyingglass")
                    .foregroundStyle(.tertiary)
                TextField("Search artifacts...", text: $searchText)
                    .textFieldStyle(.plain)
                if !searchText.isEmpty {
                    Button {
                        searchText = ""
                    } label: {
                        Image(systemName: "xmark.circle.fill")
                            .foregroundStyle(.tertiary)
                    }
                    .buttonStyle(.plain)
                }
            }
            .padding(8)
            .background(
                RoundedRectangle(cornerRadius: 8, style: .continuous)
                    .fill(Color(NSColor.controlBackgroundColor))
            )
            .frame(maxWidth: 240)

            // Type filter
            Picker("Type", selection: $filterType) {
                ForEach(ArtifactTypeFilter.allCases, id: \.self) { type in
                    Text(type.rawValue).tag(type)
                }
            }
            .pickerStyle(.segmented)
            .frame(width: 280)

            Spacer()
        }
    }

    // MARK: - Artifacts Grid

    private var artifactsGrid: some View {
        ScrollView {
            LazyVGrid(columns: [GridItem(.adaptive(minimum: 200))], spacing: 12) {
                ForEach(filteredArtifacts) { artifact in
                    ArtifactCard(
                        artifact: artifact,
                        isSelected: selectedArtifact?.id == artifact.id,
                        onSelect: {
                            withAnimation(.spring(response: 0.3)) {
                                selectedArtifact = artifact
                            }
                        },
                        onOpen: {
                            model.openArtifact(artifact)
                        }
                    )
                }
            }
        }
    }

    private var filteredArtifacts: [Artifact] {
        model.artifacts.filter { artifact in
            // Filter by search
            let matchesSearch = searchText.isEmpty ||
                artifact.filename.localizedCaseInsensitiveContains(searchText) ||
                artifact.type.localizedCaseInsensitiveContains(searchText)

            // Filter by type
            let matchesType: Bool
            switch filterType {
            case .all:
                matchesType = true
            case .image:
                matchesType = isImageType(artifact.type)
            case .document:
                matchesType = isDocumentType(artifact.type)
            case .code:
                matchesType = isCodeType(artifact.type)
            case .other:
                matchesType = !isImageType(artifact.type) && !isDocumentType(artifact.type) && !isCodeType(artifact.type)
            }

            return matchesSearch && matchesType
        }
    }

    // MARK: - Helpers

    private func isImageType(_ type: String) -> Bool {
        ["image", "png", "jpg", "jpeg", "gif", "webp", "svg"].contains { type.lowercased().contains($0) }
    }

    private func isDocumentType(_ type: String) -> Bool {
        ["pdf", "doc", "docx", "txt", "md", "markdown", "text"].contains { type.lowercased().contains($0) }
    }

    private func isCodeType(_ type: String) -> Bool {
        ["code", "script", "js", "ts", "py", "swift", "go", "rs", "json", "yaml", "yml", "xml", "html", "css"].contains { type.lowercased().contains($0) }
    }

    private func formatSize(_ bytes: Int) -> String {
        if bytes < 1024 { return "\(bytes) B" }
        let kb = Double(bytes) / 1024
        if kb < 1024 { return String(format: "%.1f KB", kb) }
        let mb = kb / 1024
        if mb < 1024 { return String(format: "%.1f MB", mb) }
        let gb = mb / 1024
        return String(format: "%.2f GB", gb)
    }

    private func refreshArtifacts() {
        isRefreshing = true
        Task {
            await model.refreshArtifacts()
            isRefreshing = false
        }
    }
}

// MARK: - Artifact Card

struct ArtifactCard: View {
    let artifact: Artifact
    let isSelected: Bool
    let onSelect: () -> Void
    let onOpen: () -> Void

    @State private var isHovered = false

    var body: some View {
        VStack(alignment: .leading, spacing: 10) {
            // Preview/Icon area
            ZStack {
                RoundedRectangle(cornerRadius: 8, style: .continuous)
                    .fill(Color(NSColor.controlBackgroundColor))
                    .frame(height: 100)

                if isImageType {
                    Image(systemName: "photo")
                        .font(.system(size: 32))
                        .foregroundStyle(.tertiary)
                } else {
                    Image(systemName: artifactIcon)
                        .font(.system(size: 32))
                        .foregroundStyle(artifactColor)
                }
            }

            // Info
            VStack(alignment: .leading, spacing: 4) {
                Text(artifact.filename)
                    .font(.subheadline.weight(.medium))
                    .lineLimit(1)
                    .truncationMode(.middle)

                HStack(spacing: 8) {
                    Label(artifact.type, systemImage: "tag")
                        .font(.caption2)
                        .foregroundStyle(.secondary)

                    Spacer()

                    Text(formatSize(artifact.size))
                        .font(.caption2)
                        .foregroundStyle(.tertiary)
                }
            }

            // Open button
            Button {
                onOpen()
            } label: {
                Label("Open", systemImage: "arrow.up.forward.square")
                    .frame(maxWidth: .infinity)
            }
            .buttonStyle(.bordered)
            .controlSize(.small)
        }
        .padding(12)
        .background(
            RoundedRectangle(cornerRadius: 12, style: .continuous)
                .fill(Color(NSColor.controlBackgroundColor))
        )
        .overlay(
            RoundedRectangle(cornerRadius: 12, style: .continuous)
                .stroke(isSelected ? artifactColor.opacity(0.5) : (isHovered ? Color.gray.opacity(0.3) : Color.gray.opacity(0.15)), lineWidth: isSelected ? 2 : 1)
        )
        .scaleEffect(isHovered ? 1.02 : 1.0)
        .animation(.spring(response: 0.3, dampingFraction: 0.8), value: isHovered)
        .onHover { hovering in
            isHovered = hovering
        }
        .onTapGesture {
            onSelect()
        }
    }

    private var isImageType: Bool {
        ["image", "png", "jpg", "jpeg", "gif", "webp", "svg"].contains { artifact.type.lowercased().contains($0) }
    }

    private var artifactIcon: String {
        let type = artifact.type.lowercased()
        if type.contains("pdf") { return "doc.fill" }
        if type.contains("doc") || type.contains("text") || type.contains("txt") { return "doc.text.fill" }
        if type.contains("code") || type.contains("script") || type.contains("json") { return "chevron.left.forwardslash.chevron.right" }
        if type.contains("zip") || type.contains("archive") { return "doc.zipper" }
        return "doc.fill"
    }

    private var artifactColor: Color {
        let type = artifact.type.lowercased()
        if type.contains("image") || type.contains("png") || type.contains("jpg") { return .purple }
        if type.contains("pdf") { return .red }
        if type.contains("doc") || type.contains("text") { return .blue }
        if type.contains("code") || type.contains("script") || type.contains("json") { return .green }
        return .secondary
    }

    private func formatSize(_ bytes: Int) -> String {
        if bytes < 1024 { return "\(bytes) B" }
        let kb = Double(bytes) / 1024
        if kb < 1024 { return String(format: "%.1f KB", kb) }
        let mb = kb / 1024
        return String(format: "%.1f MB", mb)
    }
}
